id: frigate_inside_garagem_motion_detected
alias: Frigate Motion detected Inside Garage
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    labels:
      - person
    tv_transparency: 0%
    camera: camera.inside_garagem
    state_filter: true
    state_entity: alarm_control_panel.ajax_security_system
    state_filter_states:
      - armed_home
    notify_group: ha_mobile_apps
    notify_device: c5e66df13fa3b28125099c5a4229ddc0
    base_url: https://alberto.mcunha.me/
    message: "{{ label }} detected - {{ camera_name }}"
