id: frigate_frente_motion_detected
alias: Frigate Motion detected Frente
description: ''
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frente
    notify_device: c5e66df13fa3b28125099c5a4229ddc0
    notify_group: ha_mobile_apps
    message: '{{ label }} detected - {{ camera_name }}'
    zone_filter: true
    zones:
      - Frente_Jardim
      - Frente_Portao
    state_filter: true
    state_entity: alarm_control_panel.ajax_security_system
    state_filter_states:
      - armed_home
    base_url: https://alberto.mcunha.me/
    
