id: motion_detected_frente
alias: Motion detected - Frente
mode: single
max_exceeded: silent
triggers:
  - trigger: state
    entity_id: binary_sensor.dvr_camera_frente_motion_alarm
    from: "off"
    to: "on"
    for: "00:00:02"
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.ajax_security_system
        state: armed_home
actions:
  - action: script.security_camera_alert
    data:
      camera_entity: camera.dvr_camera_frente_main
  - alias: Wait before alerting again
    delay:
      minutes: 3
