id: motion_detected_frente
alias: Motion detected - Frente
mode: single
max_exceeded: silent
variables:
  notify_device: notify.ha_mobile_apps
  trigger_entity: binary_sensor.dvr_camera_frente_motion_alarm
  doorbell_cam: camera.dvr_camera_frente_main
  notification_title: Movimento Detectado na Frente
  persistent_notification: false
  image_file: >-
    /local/doorbell/{{ expand(trigger_entity)[0].last_changed | as_timestamp  |
    timestamp_custom("%Y-%m-%d_%H-%M-%S-%f") }}.jpg
  llm_model: gemini-1.5-pro
  llm_prompt: >-
    Atua como sendo o responsável pelo meu sistema de segurança em casa.
    Descreve a imagem numa frase curta usando Português de Portugal. Se vires pessoas,
    descreve-as.
trigger:
  platform: state
  entity_id:
    - binary_sensor.dvr_camera_frente_motion_alarm
  # Optional
  from: "off"
  # Optional
  to: "on"
  # "on" for 2 seconds
  for: "00:00:02"

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.anyone_home
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.ajax_security_system
        state: armed_home

action:
  - action: camera.snapshot
    data:
      filename: >-
        /config/www/doorbell/{{ expand(trigger_entity)[0].last_changed |
        as_timestamp  | timestamp_custom("%Y-%m-%d_%H-%M-%S-%f") }}.jpg
    target:
      entity_id: "{{doorbell_cam}}"
  - action: llmvision.image_analyzer
    data:
      remember: false
      include_filename: false
      target_width: 1280
      max_tokens: 100
      temperature: 0.2
      expose_images: false
      image_file: >-
        /config/www/doorbell/{{ expand(trigger_entity)[0].last_changed |
        as_timestamp  | timestamp_custom("%Y-%m-%d_%H-%M-%S-%f") }}.jpg
      provider: 01JFTMMBPD3Y5F42RRWGGZ8W73
      message: "{{llm_prompt}}"
      model: "{{ llm_model }}"
    response_variable: llm_response
  - service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{llm_response.response_text}}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        image: "{{ image_file }}"
        ttl: 0
        priority: high
        actions:
          - action: "URI"
            title: "Open Camera"
            uri: "app://com.mm.android.DMSS"
  - delay:
      minutes: 3
