#
# Welcome to my Home Assistant configuration!
#
# This file is only used to bootstrap the system.
# You can find the rest of the configurationo inside the integrations folder.
#

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage #Dashboards in storage mode can be created in the configuration panel.
  # Add more dashboards
  dashboards:
    lovelace-tablet-dashboard: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboards/tablet.yaml
      title: Tablet
      show_in_sidebar: true
      icon: mdi:tablet
    tablet-office-dashboard: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboards/tablet-office.yaml
      title: Tablet Office
      show_in_sidebar: true
      icon: mdi:tablet
    vacuum-dashboard:
      mode: yaml
      filename: dashboards/vacuum.yaml
      title: Vacuum Cleaner
      show_in_sidebar: true
      icon: mdi:robot-vacuum
      require_admin: true
# Load Home Assistant integrations as packages
homeassistant:
  name: !secret ha_name
  unit_system: !secret ha_unit_system
  currency: !secret ha_currency
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  country: !secret ha_country
  external_url: !secret external_url
  internal_url: !secret internal_url
  allowlist_external_urls: !secret ha_allowlist_external_urls
  # Load customizations
  # Only for those device that are not customisable from UI
  customize: !include customize.yaml
  # Load packages
  packages: !include_dir_named integrations

#################################################################
## Includes
#################################################################
automation: !include_dir_list automations
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
input_boolean: !include helpers/input_boolean.yaml

hdmi_cec:
  devices:
    1: Chromecast
delete: