id: turn_off_ventax_wc_suite
alias: Turn off ventax if humitidy of WC Suite is normal
mode: restart
max_exceeded: silent
variables:
  notification_title: Humidade WC Suite
  persistent_notification: false
  send_notification: false
trigger:
  - platform: template
    value_template: >-
      {{ states('sensor.sensor_temperature_humidity_wc_suite_humidity') <
      states('input_number.bathroom_max_humidity_percentage') }}
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - platform: time_pattern
    minutes: /20
condition:
  - alias: "DND is enabled or the humidity is at a normal level"
    or:
    - condition: state
      entity_id: schedule.dnd_schedule
      state: "on"
      alias: "DND is enabled"
    - and:
      - condition: template
        value_template: |-
          {{ states('sensor.sensor_temperature_humidity_wc_suite_humidity') <
                states('input_number.bathroom_max_humidity_percentage') }}
      - condition: state
        entity_id: fan.multiswitch_wc_suite_ventax
        state: "on"
action:
  - alias: Set up variables for the actions
    variables:
      action_ack: "{{ 'ACK_' ~ context.id }}"
      message: "{{ 'Humidade na WC Suite normal: ' ~ states('sensor.sensor_temperature_humidity_wc_suite_humidity')  ~ '%. Ventilação desligada.'}}"
  - if: "{{ send_notification == true }}"
    then:
      - alias: Send notification
        service: notify.ha_mobile_apps
        data:
          title: "{{ notification_title }}"
          message: "{{ message }}"
          data:
            tag: "{{ notification_title }}"
            persistent: "{{ persistent_notification }}"
            ttl: 0
            priority: high
  - alias: Perform the action
    service: fan.turn_off
    target:
      entity_id: fan.multiswitch_wc_suite_ventax
