id: open_office_cover_if_is_too_dark
alias: Open office cover when it is too dark
description: "If it is too dark, it automatically adjusts the shutter position."
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.sensor_occupancy_office_occupancy
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    alias: When someone in the office
  - platform: numeric_state
    entity_id: sensor.sensor_occupancy_office_illuminance_lux
    for:
      hours: 0
      minutes: 2
      seconds: 0
    below: 350
    alias: When it is too dark
condition:
  - condition: sun
    before: sunset
    after: sunrise
  - condition: state
    entity_id: switch.plug_monitor
    state: "on"
    alias: Monitor is On
  - condition: state
    entity_id: input_boolean.anyone_home
    state: "on"
  - condition: numeric_state
    entity_id: cover.estores_escritorio
    attribute: current_position
    below: 75
    alias: Curtains are below 75
action:
  - service: cover.set_cover_position
    data:
      position: 75
    target:
      entity_id: cover.estores_escritorio
