id: turn_on_office_leds_if_motion_detected
alias: Turn on Office LEDs if motion is detected
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.sensor_presence_office_motion_state
    to: "large"
  - platform: state
    entity_id:
      - sensor.sensor_presence_office_motion_state
    to: "static"
  - platform: state
    entity_id:
      - binary_sensor.sensor_presence_office_presence
    to: "on"
condition:
  - condition: numeric_state
    entity_id: sensor.sensor_presence_office_illuminance
    below: 800
action:
  - service: light.turn_on
    data:
      brightness: 20
    target:
      device_id: 5e1d63d99c520bcaf7ab65d64a32e26d

