id: turn_off_swimming_pool_pump_according_to_energy_usage
alias: Turn off swimming pool pump according to the energy usage
description: "Turn off swimming pool pump according to the energy usage"
mode: restart
max_exceeded: silent
variables:
  send_notification: false
  notify_device: notify.ha_mobile_apps
  trigger_entity: binary_sensor.sensor_garage_door_contact
  notification_title: Bomba da Piscina
  persistent_notification: false
trigger:
  - platform: numeric_state
    entity_id: sensor.energy_consumption_mean_over_last_10_minutes
    above: -300
    alias: Not enough energy to have the swimming pool pump working
    #every 20 minutes
  - platform: time_pattern
    minutes: /20
condition:
  - condition: and
    conditions:
      - condition: or
        alias: "Worked desired time or not enough energy production"
        conditions:
          - condition: template
            value_template: "{{states('sensor.swimming_pool_pump_on_today')|float > states('input_number.swimming_pool_minimum_duration_h')|float}}"
            alias: Swimming pool pump has been running for the required time
          - condition: numeric_state
            entity_id: sensor.energy_consumption_mean_over_last_10_minutes
            above: -150
            alias: Not enough power for the swimming pool pump
      - condition: numeric_state
        entity_id: sensor.bomba_piscina_switch_0_power
        above: 0
        alias: Swimming pool pump working
action:
  - alias: Set up variables for the actions
    variables:
      message: "{{ 'Produção demasiado baixa, consumo: ' ~ states('sensor.energy_consumption_mean_over_last_10_minutes')  ~ 'W. Desligada automaticamente.'}}"
  - alias: Perform the action
    service: switch.turn_off
    target:
      device_id: 11352414f861aaceba25adee16b975f5
  - if: "{{ send_notification == true }}"
    then:
      - alias: Send a message to mobile app
        choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{states('sensor.swimming_pool_pump_on_today')|float >
                  states('input_number.swimming_pool_minimum_duration_h')|float}}
                alias: Swimming Pool pump already worked the desired time
            sequence:
              - alias: Inform swimming pool pump was turned off due to time usage
                service: notify.ha_mobile_apps
                data:
                  title: "{{ notification_title }}"
                  message: "{{ 'Bomba já trabalhou : ' ~ states('sensor.swimming_pool_pump_on_today')|float  ~ 'h. Desligada automaticamente.'}}"
                  data:
                    tag: "{{ notification_title }}"
                    persistent: "{{ persistent_notification }}"
                    ttl: 0
                    priority: high
          - conditions:
              - condition: numeric_state
                entity_id: sensor.average_consumption_inc_pool_pump
                above: -150
            sequence:
              - alias: Inform swimming pool pump was turned off due to energy usage
                service: notify.ha_mobile_apps
                data:
                  title: "{{ notification_title }}"
                  message: "{{ message }}"
                  data:
                    tag: "{{ notification_title }}"
                    persistent: "{{ persistent_notification }}"
                    ttl: 0
                    priority: high
