id: send_notification_toaster_is_on
alias: Send notification if toaster is on
mode: restart
max_exceeded: silent
variables:
  notification_title: Torradeira ligada
  persistent_notification: true
triggers:
  - trigger: state
    entity_id:
      - switch.torradeira_plug
    to: "on"
    for: "00:05:00"
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: state
    entity_id: switch.torradeira_plug
    state: "on"
  - "{{ state_attr('input_datetime.toaster_on_since', 'timestamp') is not none and now().timestamp() - state_attr('input_datetime.toaster_on_since', 'timestamp') >= 300 }}"
actions:
  - alias: Set up variables for the actions
    variables:
      action_turnoff: "{{ 'TURN_OFF_' ~ context.id }}"
      action_ignore: "{{ 'IGNORE_' ~ context.id }}"
  - alias: Ask to turn off the toaster
    action: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: Torradeira ligada por mais de 5 minutos. Pretende desligar?
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: high
        actions:
          - action: "{{ action_turnoff }}"
            title: Desligar
          - action: "{{ action_ignore }}"
            title: Ignorar
  - alias: Wait for the answer
    wait_for_trigger:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_turnoff }}"
    timeout:
      minutes: 5
    continue_on_timeout: false
  - alias: Turn off the toaster
    action: switch.turn_off
    target:
      entity_id: switch.torradeira_plug
