id: toaster_turn_off_automatically
alias: Turn off toaster automatically after 10min
mode: restart
max_exceeded: silent
variables:
  notification_title: Torradeira desligada
  persistent_notification: false
triggers:
  - trigger: time_pattern
    minutes: /1
conditions:
  - condition: state
    entity_id: switch.torradeira_plug
    state: "on"
  - "{{ state_attr('input_datetime.toaster_on_since', 'timestamp') is not none and now().timestamp() - state_attr('input_datetime.toaster_on_since', 'timestamp') >= 600 }}"
actions:
  - action: switch.turn_off
    target:
      entity_id: switch.torradeira_plug
  - alias: Notify toaster is off
    action: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: Torradeira desligada automaticamente.
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: NORMAL
