covers_cool_down_mode:
  alias: Set covers position to cool down mode
  mode: single
  sequence:
    - alias: "Set variables"
      variables:
        entities:
          - cover.curtains_kitchen
          - cover.curtains_livingroom_right
          - cover.curtains_livingroom_left
          - cover.curtains_suite
          - cover.curtains_hall
        desired_position_percentage: 30
    - service: cover.set_cover_position
      data:
        position: "{{ desired_position_percentage }}"
      target:
        entity_id: "{{ entities }}"
    - service: input_text.set_value
      data:
        value: COOL_DOWN
      target:
        entity_id: input_text.active_mode
