covers_cool_down_mode:
  alias: Set covers position to cool down mode
  mode: single
  sequence:
    - alias: "Set variables"
      variables:
        active_mode: COOL_DOWN
        entities:
          - cover.curtains_kitchen
          - cover.curtains_livingroom_right
          - cover.curtains_livingroom_left
          - cover.curtains_suite
          - cover.curtains_hall
        desired_position_percentage: 30
    - action: input_text.set_value
      data:
        value: "{{active_mode}}"
      target:
        entity_id: input_text.active_mode
    - action: cover.set_cover_position
      target:
        entity_id: "{{ entities }}"
      data:
        position: "{{ desired_position_percentage }}"
    - action: input_text.set_value
      data:
        value:
      target:
        entity_id: input_text.active_mode
