turn_on_exterior_led:
  alias: Turn on exterior LED for a given duration (default 5min)
  icon: mdi:lightbulb-fluorescent-tube-outline
  mode: restart
  max_exceeded: silent
  fields: 
      duration:
        description: Duration (min) that the light will be on
        default: 5
        example: "5"
  sequence:
    - if:
        - condition: sun
          after: sunset
          before: sunrise
      then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.barra_led_exterior_switch_0
        - delay:
            hours: 0
            minutes: "{{ duration }}"
            seconds: 0
            milliseconds: 0
        - service: switch.turn_off
          data: {}
          target:
            entity_id: switch.barra_led_exterior_switch_0
        - delay:
            hours: 0
            minutes: 5
            seconds: 0
            milliseconds: 0
    

