mode_night:
  alias: Set the entities according to the night mode
  mode: single
  sequence:
    - alias: "Set variables"
      variables:
        active_mode: NIGHT
        entities_to_close:
          - cover.curtains_livingroom_right
          - cover.curtains_livingroom_left
          - cover.estores_escritorio
          - cover.curtains_guestroom
          - cover.estores_lavandaria
          - cover.curtains_suite
          - cover.curtains_wcsuite
          - cover.curtains_hall
        curtains_to_close_partially: []
        desired_position_percentage: 20
        switches_to_turn_off: []
        lights_to_turn_off: []
        lights_to_turn_on:
          - light.zigbee_smartpowerplug_1 # Luz presença Marco
          - light.candeeiro_ambiente_2 # Candeeiro ambiente
          - light.switch_tomada_poltrona # Luz tomada poltrona
          - light.plug_candeeiro_presenca_hall # Candeeiro presença hall

    - alias: "Set active mode"
      action: input_text.set_value
      data:
        value: "{{ active_mode }}"
      target:
        entity_id: input_text.active_mode

    - alias: "Close covers"
      action: cover.close_cover
      target:
        entity_id: "{{ entities_to_close | default([]) }}"

    - alias: "Set cover position for partial close"
      action: cover.set_cover_position
      data:
        position: "{{ desired_position_percentage }}"
      target:
        entity_id: "{{ curtains_to_close_partially | default([]) }}"

    - alias: "Turn OFF specified switches"
      action: switch.turn_off
      target:
        entity_id: "{{ switches_to_turn_off | default([]) }}"

    - alias: "Turn OFF specified lights"
      action: light.turn_off
      target:
        entity_id: "{{ lights_to_turn_off | default([]) }}"

    - alias: "Turn ON specified lights"
      action: light.turn_on
      target:
        entity_id: "{{ lights_to_turn_on | default([]) }}"
