mode_sleep:
  alias: Set the entities according to the sleep mode
  mode: single
  sequence:
    - alias: "Set variables"
      variables:
        active_mode: SLEEP
        entities_to_close:
          - cover.curtains_livingroom_right
          - cover.curtains_livingroom_left
          - cover.estores_escritorio
          - cover.curtains_guestroom
          - cover.estores_lavandaria
          - cover.curtains_suite
          - cover.curtains_wcsuite
          - cover.curtains_hall
          - cover.curtains_kitchen
        desired_position_percentage: 13
        lights_to_turn_off:
          - light.projectores_piscina
          - light.candeeiro_ambiente_2
          - light.switch_tomada_poltrona
          - light.light_office_leds
          - light.office_light
          - light.multiswitch_wc_guests_left
          - light.multiswitch_wc_guests_right
          - light.multiswitch_wc_suite_ceiling
          - light.multiswitch_wc_suite_mirror
          - light.suite_lights
          - light.plug_candeeiro_presenca_hall
        lights_to_turn_on:
    - action: input_text.set_value
      data:
        value: "{{active_mode}}"
      target:
        entity_id: input_text.active_mode
    - action: cover.close_cover
      alias: Close covers
      data: {}
      target:
        entity_id: "{{ entities_to_close }}"
    - action: light.turn_off
      alias: Turn OFF certain lights
      data: {}
      target:
        entity_id: "{{ lights_to_turn_off }}"
    - action: light.turn_on
      alias: Turn ON certain lights
      data: {}
      target:
        entity_id: "{{ lights_to_turn_on }}"
