# https://www.home-assistant.io/integrations/script/

# Map of rooms:
#
# 1 - Cozinha
# 2 - Lavandaria
# 4 - Sala
# 5 - WC-Visitas
# 6 - Escritório
# 7 - Hall
# 8 - Suite
# 9 - WC-Suite
# 10 - Quarto Visitas

vacuum_clean_social_areas:
  alias: Vacuum Clean Social Areas
  icon: mdi:sofa
  sequence:
    - service: dreame_vacuum.vacuum_clean_segment
      data:
        segments:
          - 1
          - 2
          - 4
      target:
        entity_id: vacuum.l40s_pro_ultra

vacuum_clean_private_areas:
  alias: Vacuum Clean Private Areas
  icon: mdi:bed
  sequence:
    - service: dreame_vacuum.vacuum_clean_segment
      data:
        segments:
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
      target:
        entity_id: vacuum.l40s_pro_ultra
