template:
  - cover:
      - device_class: garage
        open_cover:
          service: script.garage
        close_cover:
          service: script.garage
        name: "Garage Door"
        state: "{{ states('binary_sensor.sensor_garage_door_contact') == 'on'}}"
        icon: >-
          {% if states('binary_sensor.sensor_garage_door_contact') == "on" %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
