#
# InfluxDB
#
# https://www.home-assistant.io/integrations/influxdb/
#

influxdb:
  tags:
    source: HomeAssistant
  tags_attributes:
    - friendly_name
  default_measurement: state
  ignore_attributes:
    - icon
  exclude:
    domains:
      - updater
      - automation
      - calendar
      - camera
      - media_player
      - remote
    entities:
      - sun.sun
    entity_globs:
      - device_tracker.*
