#
# Input Number

#
# https://www.home-assistant.io/integrations/input_number/
#
input_number:
  swimming_pool_minimum_duration_h:
    name: Swimming Pool Pump Minimum Duration in h
    initial: 12
    min: 0
    max: 99
    step: 1
    mode: box
  swimming_pool_average_consumption_w:
    name: Swimming Pool Pump Average Consumption in W
    initial: 750
    min: 700
    max: 800
    step: 1
    mode: box
  bathroom_max_humidity_percentage:
    name: Max Humidity in Bathroom
    initial: !secret CONST_MAX_BATHROOM_HUMIDITY
    min: 0
    max: 999
    step: 1
    mode: box
  desired_hot_water_temperature:
    name: Desired hot water temperature
    initial: !secret CONST_DESIRED_HOT_WATER_TEMPERATURE
    min: 0
    max: 80
    step: 1
    mode: box
  static_price_per_kwh:
    name: Static price per KWh
    initial: !secret CONST_PRICE_PER_KWH
    min: 0
    max: 100
    step: 0.01
    mode: box
    unit_of_measurement: EUR/kWh
