schedule:
  dnd_schedule:
    name: "Do Not Disturb schedule"
    monday:
      - from: "00:00:00"
        to: "7:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    tuesday:
      - from: "00:00:00"
        to: "7:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    wednesday:
      - from: "00:00:00"
        to: "7:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    thursday:
      - from: "00:00:00"
        to: "7:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    friday:
      - from: "00:00:00"
        to: "7:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    saturday:
      - from: "00:00:00"
        to: "9:30:00"
      - from: "21:30:00"
        to: "24:00:00"
    sunday:
      - from: "00:00:00"
        to: "9:30:00"
      - from: "21:30:00"
        to: "24:00:00"
