schedule:
  swimming_pool_pump_schedule:
    name: "Swimming Pool Pump schedule"
    monday:
      - from: "10:00:00"
        to: "17:00:00"
    tuesday:
      - from: "10:00:00"
        to: "17:00:00"
    wednesday:
      - from: "10:00:00"
        to: "17:00:00"
    thursday:
      - from: "10:00:00"
        to: "17:00:00"
    friday:
      - from: "10:00:00"
        to: "17:00:00"
    saturday:
      - from: "10:00:00"
        to: "17:00:00"
    sunday:
      - from: "10:00:00"
        to: "17:00:00"
