id: clear_active_mode
alias: Clear Active Mode
mode: single
description: Clears Active Mode Input Helper
trigger:
  - platform: time
    at: 07:00:00
condition: []
action:
  - service: input_text.set_value
    metadata: {}
    data:
      value: ""
    target:
      entity_id: input_text.active_mode
