id: clear_active_mode
alias: Clear Active Mode
mode: single
description: Clears Active Mode Input Helper
triggers:
  - trigger: time
    at: 07:00:00
actions:
  - action: input_text.set_value
    data:
      value: ""
    target:
      entity_id: input_text.active_mode
