id: clear_force_hot_water_helpers
alias: Clear Force Hot Water Helpers
mode: single
description: Clears Force Hot Water Helpers
triggers:
  - trigger: time
    at:
      - "00:00:00"
      - "10:00:00"
      - "20:00:00"
actions:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.force_hot_water_off
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.force_hot_water_on
