id: set_both_home_on
alias: Both at home ON
description: "Set both_home to on when both at home"
mode: single
triggers:
  - trigger: state
    entity_id:
      - person.darlene_parreira
      - person.marco_cunha
    to: home
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.marco_cunha
        state: home
      - condition: state
        entity_id: person.darlene_parreira
        state: home
actions:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.both_home
