id: set_both_home_off
alias: Both at home OFF
description: "Set both_home to OFF when both are not at home"
mode: single
triggers:
  - trigger: state
    entity_id:
      - person.marco_cunha
      - person.darlene_parreira
    to: not_home
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.marco_cunha
        state: not_home
      - condition: state
        entity_id: person.darlene_parreira
        state: not_home
actions:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.both_home
